"""
ALSA helper utilities
- Detect WM8960/seeed-2mic card index
- Generate a minimal ALSA config to avoid noisy defaults
"""

from __future__ import annotations

import os
from typing import Iterable, Optional


DEFAULT_CARD_KEYWORDS = (
    "seeed-2mic-voicecard",
    "seeed2micvoicec",
    "wm8960",
    "i2s-wm8960",
)


def _detect_alsa_card_index(keywords: Iterable[str] = DEFAULT_CARD_KEYWORDS) -> Optional[int]:
    cards_path = "/proc/asound/cards"
    try:
        with open(cards_path, "r", encoding="utf-8") as f:
            data = f.read()
    except OSError:
        return None

    for line in data.splitlines():
        lower = line.lower()
        if any(k in lower for k in keywords):
            parts = line.strip().split()
            if parts and parts[0].isdigit():
                return int(parts[0])
    return None


def _render_minimal_alsa_config(card_index: int) -> str:
    lines = []
    # 必须加载系统默认配置，否则 'type plug' 等定义会丢失
    if os.path.exists("/usr/share/alsa/alsa.conf"):
        lines.append("</usr/share/alsa/alsa.conf>")
    
    lines.append("# Auto-generated by VigiDoor")
    lines.append(f"defaults.pcm.card {card_index}")
    lines.append(f"defaults.ctl.card {card_index}")
    lines.append("")
    lines.append("pcm.!default {")
    lines.append("  type plug")
    lines.append(f"  slave.pcm \"hw:{card_index},0\"")
    lines.append("}")
    lines.append("")
    lines.append("ctl.!default {")
    lines.append("  type hw")
    lines.append(f"  card {card_index}")
    lines.append("}")
    
    return "\n".join(lines)


def setup_alsa_defaults(logger=None) -> Optional[str]:
    """
    Setup a minimal ALSA config to avoid noisy default device probing.

    Returns the config path if applied, else None.
    """
    if os.environ.get("ALSA_CONFIG_PATH"):
        return None

    card_index = _detect_alsa_card_index()
    if card_index is None:
        return None

    config_path = f"/tmp/vigidoor_alsa_{card_index}.conf"
    config_content = _render_minimal_alsa_config(card_index)

    try:
        existing = None
        if os.path.exists(config_path):
            with open(config_path, "r", encoding="utf-8") as f:
                existing = f.read()
        if existing != config_content:
            with open(config_path, "w", encoding="utf-8") as f:
                f.write(config_content)
    except OSError as e:
        if logger:
            logger.warning(f"写入 ALSA 配置失败: {e}")
        return None

    os.environ.setdefault("ALSA_CONFIG_PATH", config_path)
    os.environ.setdefault("ALSA_CARD", str(card_index))
    os.environ.setdefault("ALSA_PCM_CARD", str(card_index))
    os.environ.setdefault("ALSA_CTL_CARD", str(card_index))

    if logger:
        logger.info(f"已应用 ALSA 最小配置: {config_path} (card {card_index})")
    return config_path
